CREATE SEQUENCE SQ_CARGO
START WITH 1
INCREMENT BY 1
MAXVALUE 999
NOCACHE
NOCYCLE;

CREATE SEQUENCE SQ_PROJ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
NOCACHE
NOCYCLE;

INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'PROGRAMADOR',3000.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'ANALISTA DE SISTEMAS',5700.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'ANALISTA FINANCEIRO',4200.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'GERENTE DE RH',6100.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'CONTADOR',3400.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'ENGENHEIRO',9300.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'ADMINISTRADOR',3900.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'PUBLICITÁRIO',4400.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'MOTORISTA',1800.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'SECRETÁRIA',1350.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'AUXILIAR DE SERVIÇOS GERAIS',1230.00);
INSERT INTO CARGO VALUES (SQ_CARGO.NEXTVAL,'DBA',12600.00);

COMMIT;

INSERT INTO DEPARTAMENTO VALUES ('TI','TECNOLOGIA DA INFORMAÇÃO');
INSERT INTO DEPARTAMENTO VALUES ('ADM','ADMINISTRAÇÃO');
INSERT INTO DEPARTAMENTO VALUES ('MKT','MARKETING');
INSERT INTO DEPARTAMENTO VALUES ('ENG','ENGENHARIA');
INSERT INTO DEPARTAMENTO VALUES ('FIN','FINANCEIRO');
INSERT INTO DEPARTAMENTO VALUES ('RH','RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTO VALUES ('CTB','CONTABILIDADE');

COMMIT;


INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Atualização WIN10',30000.00,6,'TI');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Migração MS Outlook',17000.00,4,'TI');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Plano Cargos e Salários',80000.00,24,'RH');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Redes Sociais',55000.00,12,'MKT');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Aquisição de Novos Equipamentos',210000.00,30,'ENG');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Renovação móveis do escritório',120000.00,8,'ADM');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Desenvolvimento Intranet',220000.00,12,'TI');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Implantação novo E-Social',3000.00,2,'CTB');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Energia Solar',420000.00,7,'ENG');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Renovação frota veicular',650000.00,24,'ADM');
INSERT INTO PROJETO VALUES (SQ_PROJ.NEXTVAL,'Budget anual',3460000.00,12,'FIN');

COMMIT;

